spring:
  config:
    activate:
      on-profile: prod

  # Base de donn√©es PostgreSQL
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.icgyxciqajkwsyjtoiib.supabase.co}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Supabase configuration
supabase:
  url: ${SUPABASE_URL:https://icgyxciqajkwsyjtoiib.supabase.co}
  bucket: ${SUPABASE_BUCKET:videos}
  api:
    key: ${SUPABASE_API_KEY}

app:
  storage:
    type: supabase